name: CleanApp

settings:
  MARKETING_VERSION: "0.1.0"
  SWIFT_VERSION: 5.7
  VERSIONING_SYSTEM: "apple-generic"
  CLANG_ENABLE_OBJC_WEAK: "YES"
  ARCHS: $(ARCHS_STANDARD)

options:
  xcodeVersion: "14.3.1"
  bundleIdPrefix: com.devmeist3r
  createIntermediateGroups: true
  generateEmptyDirectories: true
  developmentLanguage: "pt-BR"
  deploymentTarget:
    iOS: 13.0
    macOS: 12.0

configs:
  Debug: debug
  Release: release

packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire.git
    from: 5.6.1

targets:
  Domain:
    templates:
      - CrossPlatform

  Data:
    templates:
      - CrossPlatform
    dependencies:
      - target: Domain_iOS
  DataTests:
    templates:
      - CrossPlatformTests
    dependencies:
      - target: Validation
      - target: Presentation_iOS

  Infra:
    templates:
      - CrossPlatform
    dependencies:
      - target: Data_iOS
      - target: Validation
      - package: Alamofire
  InfraTests:
    templates:
      - CrossPlatformTests
    dependencies:
      - package: Alamofire
      - target: Validation
      - target: Infra_macOS

  Presentation:
    templates:
      - CrossPlatform
    dependencies:
      - target: Domain_iOS
      - target: Data_macOS
      - target: Data_iOS
  PresentationTests:
    templates:
      - CrossPlatformTests
    dependencies:
      - target: Presentation_iOS
      - target: Domain_iOS
      - target: Validation
      - target: Data_macOS

  UseCaseIntegrationTests:
    templates:
      - MacFrameworkTests
    dependencies:
      - target: Data_iOS
      - target: Domain_iOS
      - target: Infra_iOS

  UI:
    templates:
      - iOSFramework
    dependencies:
      - target: Presentation_iOS
      - target: Data_iOS
  UITests:
    templates:
      - iOSFrameworkTests
    dependencies:
      - target: UI
      - target: Data_iOS
      - target: Presentation_iOS

  Validation:
    templates:
      - MacFramework
    dependencies:
      - target: Presentation_macOS
      - target: Data_macOS
  ValidationTests:
    templates:
      - MacFrameworkTests
    dependencies:
      - target: Validation
      - target: Presentation_macOS
      - target: Data_macOS

  Main:
    templates:
      - iOSApp
    dependencies:
      - target: Domain_iOS
      - target: Data_iOS
      - target: Infra_iOS
      - target: Presentation_iOS
      - target: UI
      - target: Validation
  MainTests:
    templates:
      - iOSAppTests
    dependencies:
      - target: Main
      - target: UI
      - target: Presentation_iOS

schemes:
  Domain:
    build:
      targets:
        Domain_iOS: [run, test]
    run:
      config: Debug

  Data:
    build:
      targets:
        Data_iOS: [run, test]
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - Data_iOS
      targets:
        - name: DataTests_iOS
          randomExecutionOrder: true

  Infra:
    build:
      targets:
        Infra_iOS: [run, test]
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - Infra_iOS
      targets:
        - name: InfraTests_iOS
          randomExecutionOrder: true

  Presentation:
    build:
      targets:
        Presentation_iOS: [run, test]
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - Presentation_iOS
      targets:
        - name: PresentationTests_iOS
          randomExecutionOrder: true

  UI:
    build:
      targets:
        UI: [run, test]
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - UI
      targets:
        - name: UITests
          randomExecutionOrder: true

  Validation:
    build:
      targets:
        Validation: [run, test]
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - Validation
      targets:
        - name: ValidationTests
          randomExecutionOrder: true

  Main:
    build:
      targets:
        Main: [run, test, archive]
    archive:
      config: Release
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - Main
      targets:
        - name: MainTests
          randomExecutionOrder: true

  CI:
    build:
      targets:
        Domain_iOS: [run, test]
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - Domain_iOS
        - Data_iOS
        - Infra_iOS
        - Presentation_iOS
        - Validation
        - UI
        # - Main
      targets:
        - name: DataTests_iOS
        - name: InfraTests_iOS
        - name: PresentationTests_iOS
        - name: Validation
        - name: UI
          # - name: MainTests
          randomExecutionOrder: true

  Core:
    build:
      targets:
        Domain_macOS: [run, test]
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - Validation
        - Domain_macOS
        - Data_macOS
        - Infra_macOS
        - Presentation_macOS
      targets:
        - name: ValidationTests
        - name: DataTests_macOS
        - name: InfraTests_macOS
        - name: PresentationTests_macOS
          randomExecutionOrder: true

targetTemplates:
  MacFramework:
    platform: macOS
    type: framework
    sources:
      - path: CleanApp/${target_name}
    info:
      path: CleanApp/${target_name}/Info.plist

  MacFrameworkTests:
    platform: macOS
    type: bundle.unit-test
    sources:
      - path: CleanApp/${target_name}
      - path: CleanApp/XCTestCase/
    info:
      path: CleanApp/${target_name}/Info.plist

  iOSFramework:
    platform: iOS
    type: framework
    sources:
      - path: CleanApp/${target_name}
    info:
      path: CleanApp/${target_name}/Info.plist

  iOSFrameworkTests:
    platform: iOS
    type: bundle.unit-test
    sources:
      - path: CleanApp/${target_name}
      - path: CleanApp/XCTestCase/
        createIntermediateGroups: false
        type: group
    info:
      path: CleanApp/${target_name}/Info.plist

  CrossPlatform:
    platform: [macOS, iOS]
    type: framework
    sources:
      - path: CleanApp/${target_name}
    info:
      path: CleanApp/${target_name}/Info.plist

  CrossPlatformTests:
    platform: [macOS, iOS]
    type: bundle.unit-test
    sources:
      - path: CleanApp/${target_name}
      - path: CleanApp/XCTestCase/
        createIntermediateGroups: false
        type: group
    info:
      path: CleanApp/${target_name}/Info.plist

  iOSApp:
    platform: iOS
    type: application
    sources:
      - path: CleanApp/${target_name}
    settings:
      INFOPLIST_FILE: CleanApp/${target_name}/Info.plist

  iOSAppTests:
    platform: iOS
    type: bundle.unit-test
    sources:
      - path: CleanApp/${target_name}
      - path: CleanApp/XCTestCase/
        createIntermediateGroups: false
        type: group
    info:
      path: CleanApp/${target_name}/Info.plist
