name: CleanApp

settings:
  MARKETING_VERSION: "0.1.0"
  SWIFT_VERSION: 5.7
  VERSIONING_SYSTEM: "apple-generic"
  CLANG_ENABLE_OBJC_WEAK: "YES"
  ARCHS: $(ARCHS_STANDARD)

options:
  xcodeVersion: "14.3.1"
  bundleIdPrefix: com.devmeist3r
  createIntermediateGroups: true
  generateEmptyDirectories: true
  developmentLanguage: "pt-BR"
  deploymentTarget:
    iOS: 13.0
    macOS: 12.0

configs:
  Debug: debug
  Release: release

packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire.git
    from: 5.6.1

targets:
  Domain:
    templates:
      - MacFramework

  Data:
    templates:
      - MacFramework
    dependencies:
      - target: Domain
  DataTests:
    templates:
      - MacFrameworkTests

  Infra:
    templates:
      - MacFramework
    dependencies:
      - target: Data
      - package: Alamofire
  InfraTests:
    templates:
      - MacFrameworkTests
    dependencies:
      - package: Alamofire

  UseCaseIntegrationTests:
    templates:
      - MacFrameworkTests
    dependencies:
      - target: Data
      - target: Domain
      - target: Infra

schemes:
  Data:
    build:
      targets:
        Data: [run, test]
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - Data
      targets:
        - name: DataTests
          randomExecutionOrder: true

  Infra:
    build:
      targets:
        Infra: [run, test]
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - Infra
      targets:
        - name: InfraTests
          randomExecutionOrder: true

targetTemplates:
  MacFramework:
    platform: macOS
    type: framework
    sources:
      - path: CleanApp/${target_name}
    info:
      path: CleanApp/${target_name}/Info.plist

  MacFrameworkTests:
    platform: macOS
    type: bundle.unit-test
    sources:
      - path: CleanApp/${target_name}
      - path: CleanApp/XCTestCase/
    info:
      path: CleanApp/${target_name}/Info.plist
