name: CleanApp

settings:
  MARKETING_VERSION: "0.1.0"
  SWIFT_VERSION: 5.7
  VERSIONING_SYSTEM: "apple-generic"
  CLANG_ENABLE_OBJC_WEAK: "YES"
  ARCHS: $(ARCHS_STANDARD)

options:
  xcodeVersion: "14.3.1"
  bundleIdPrefix: com.devmeist3r
  createIntermediateGroups: true
  generateEmptyDirectories: true
  developmentLanguage: "pt-BR"
  deploymentTarget:
    iOS: 13.0
    macOS: 12.0

configs:
  Debug: debug
  Release: release

packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire.git
    from: 5.6.1

targets:
  Domain:
    templates:
      - CrossPlatform

  Data:
    templates:
      - CrossPlatform
    dependencies:
      - target: Domain_macOS
      - target: Domain_iOS
  DataTests:
    templates:
      - CrossPlatformTests

  Infra:
    templates:
      - MacFramework
    dependencies:
      - target: Data_macOS
      - package: Alamofire
  InfraTests:
    templates:
      - MacFrameworkTests
    dependencies:
      - package: Alamofire
      - target: Infra

  Presentation:
    templates:
      - CrossPlatform
    dependencies:
      - target: Domain_macOS
      - target: Domain_iOS
      - target: Data_macOS
  PresentationTests:
    templates:
      - CrossPlatformTests
    dependencies:
      - target: Presentation_macOS
      - target: Data_macOS
      - target: Domain_macOS

  UseCaseIntegrationTests:
    templates:
      - MacFrameworkTests
    dependencies:
      - target: Data_macOS
      - target: Domain_macOS
      - target: Domain_iOS
      - target: Infra

  UI:
    templates:
      - iOSFramework
    dependencies:
      - target: Presentation_iOS
      - target: Data_iOS
  UITests:
    templates:
      - iOSFrameworkTests
    dependencies:
      - target: UI
      - target: Data_macOS
      - target: Presentation_macOS

  Validation:
    templates:
      - MacFramework
    dependencies:
      - target: Presentation_macOS
  ValidationTests:
    templates:
      - MacFrameworkTests
    dependencies:
      - target: Presentation_macOS

schemes:
  Domain:
    build:
      targets:
        Domain_macOS: [run, test]
    run:
      config: Debug

  Data:
    build:
      targets:
        Data_macOS: [run, test]
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - Data_macOS
      targets:
        - name: DataTests_macOS
          randomExecutionOrder: true

  Infra:
    build:
      targets:
        Infra: [run, test]
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - Infra
      targets:
        - name: InfraTests
          randomExecutionOrder: true

  Presentation:
    build:
      targets:
        Presentation_macOS: [run, test]
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - Presentation_macOS
      targets:
        - name: PresentationTests_macOS
          randomExecutionOrder: true

  UI:
    build:
      targets:
        UI: [run, test]
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - UI
      targets:
        - name: UITests
          randomExecutionOrder: true

  Validation:
    build:
      targets:
        Validation: [run, test]
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - Validation
      targets:
        - name: ValidationTests
          randomExecutionOrder: true

targetTemplates:
  MacFramework:
    platform: macOS
    type: framework
    sources:
      - path: CleanApp/${target_name}
    info:
      path: CleanApp/${target_name}/Info.plist

  MacFrameworkTests:
    platform: macOS
    type: bundle.unit-test
    sources:
      - path: CleanApp/${target_name}
      - path: CleanApp/XCTestCase/
    info:
      path: CleanApp/${target_name}/Info.plist

  iOSFramework:
    platform: iOS
    type: framework
    sources:
      - path: CleanApp/${target_name}
    info:
      path: CleanApp/${target_name}/Info.plist

  iOSFrameworkTests:
    platform: iOS
    type: bundle.unit-test
    sources:
      - path: CleanApp/${target_name}
      - path: CleanApp/XCTestCase/
        createIntermediateGroups: false
        type: group
    info:
      path: CleanApp/${target_name}/Info.plist

  CrossPlatform:
    platform: [macOS, iOS]
    type: framework
    sources:
      - path: CleanApp/${target_name}
    info:
      path: CleanApp/${target_name}/Info.plist

  CrossPlatformTests:
    platform: [macOS, iOS]
    type: bundle.unit-test
    sources:
      - path: CleanApp/${target_name}
      - path: CleanApp/XCTestCase/
        createIntermediateGroups: false
        type: group
    info:
      path: CleanApp/${target_name}/Info.plist
